
name: Package Module Artifact

on:
  workflow_dispatch:
  release:
    types: [created,published,released]

jobs:

  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: Dump env
      run: env | sort
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  packageModule:
    #permissions: write-all
    name: Package Module Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip artifact for deployment
        run: zip psPodTester-${{ github.event.release.tag_name }}.zip ./psPodTester/* -r
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: psPodTester-${{ github.event.release.tag_name }}.zip
          github_token: ${{ secrets.GITHUB_TOKEN }}
